let DATA=null, items=[];const $=id=>document.getElementById(id);
fetch('data/reports.json').then(r=>r.json()).then(d=>{DATA=d;buildItems();renderCards(items)}).catch(e=>{$('cards').innerHTML='<div class="notice">Data file load হয়নি। GitHub Pages-এ /data/reports.json ঠিকভাবে আপলোড হয়েছে কি না দেখুন।</div>'});
function buildItems(){items=[];(DATA.excel_sheets||[]).forEach((s,i)=>items.push({id:'e'+i,type:'excel',title:s.name,meta:`Excel Sheet · ${s.rows} rows × ${s.cols} columns`,data:s}));(DATA.documents||[]).forEach((d,i)=>(d.tables||[]).forEach((t,j)=>items.push({id:`d${i}-${j}`,type:'docs',title:d.name+(d.tables.length>1?` · ছক ${j+1}`:''),meta:`Document table · ${t.length} rows × ${t[0]?.length||0} columns`,data:{...d,table:t}})))}
function renderCards(list){$('viewer').classList.add('hidden');$('cards').innerHTML=list.map(x=>`<article class="card" data-id="${x.id}"><span class="tag">${x.type==='excel'?'Excel Sheet':'Report Document'}</span><h3>${esc(x.title)}</h3><p>${esc(x.meta)}</p></article>`).join('')||'<div class="notice">কোনো ছক পাওয়া যায়নি।</div>';document.querySelectorAll('.card').forEach(c=>c.onclick=()=>openItem(c.dataset.id))}
function openItem(id){const x=items.find(a=>a.id===id);if(!x)return;$('cards').innerHTML='';$('viewer').classList.remove('hidden');$('title').textContent=x.title;$('meta').textContent=x.meta;$('content').innerHTML=x.type==='excel'?renderExcel(x.data):renderDoc(x.data);window.scrollTo({top:0,behavior:'smooth'})}
function renderExcel(s){let html='<div class="notice">মূল Excel cell structure সংরক্ষিত হয়েছে। Formula cell হলুদে দেখানো হয়েছে; formula-র cached value থাকলে সেটিও দেখানো হয়েছে।</div><div class="tableWrap"><table class="reportTable"><tbody>';for(let r=0;r<s.cells.length;r++){html+='<tr>';for(let c=0;c<s.cells[r].length;c++){let v=s.cells[r][c];let f=typeof v==='string'&&v.startsWith('=');let cached=s.cached?.[r]?.[c];let show=f?(cached!==null&&cached!==undefined?cached:v):(v??'');html+=`<td class="${f?'formula':''}" title="${f?esc(v):''}">${esc(show)}${f?`<small>${esc(v)}</small>`:''}</td>`}html+='</tr>'}return html+'</tbody></table></div>'}
function renderDoc(d){let t=d.table||d.tables?.[0]||[];let h='<div class="notice">এই ছকটি সরবরাহ করা Document থেকে নেওয়া হয়েছে। Source text-এর বিন্যাস যতটা সম্ভব অক্ষুণ্ণ রাখা হয়েছে।</div><div class="tableWrap"><table class="reportTable"><tbody>';t.forEach((row,i)=>{h+='<tr>'+row.map(c=>`<td>${esc(c||'')}</td>`).join('')+'</tr>'});return h+'</tbody></table></div>'}
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
$('search').oninput=()=>{const q=$('search').value.trim().toLowerCase(),src=$('source').value;renderCards(items.filter(x=>(src==='all'||x.type===src)&&(!q||x.title.toLowerCase().includes(q)||x.meta.toLowerCase().includes(q))))};$('source').onchange=()=>$('search').dispatchEvent(new Event('input'));$('allBtn').onclick=()=>{ $('search').value='';$('source').value='all';renderCards(items)};$('back').onclick=()=>renderCards(items);
